# Run warsaw docker image that allows Internet Baking on Banco do Brasil
alias docker_bb='docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/Documentos/Outros/ArquivosDoBanco:/home/bank/Downloads -e DISPLAY=unix$DISPLAY --shm-size 2g --name warsaw-browser lichti/warsaw-browser bb'

# Enable ignore-case searching in the integration between synapse-mlocate
alias mlocate='mlocate --ignore-case'
