# ANDROID_HOME
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=${PATH}:$ANDROID_HOME/tools
export PATH=${PATH}:$ANDROID_HOME/tools/bin
export PATH=${PATH}:$ANDROID_HOME/platform-tools
export PATH=${PATH}:$ANDROID_HOME/build-tools/28.0.3

# AUTOJUMP
[[ -s /usr/share/autojump/autojump.sh ]] && source /usr/share/autojump/autojump.sh

# PYENV
export PYTHON_CONFIGURE_OPTS="--enable-shared"

# FZF
export FZF_DEFAULT_OPTS="--reverse --inline-info"
export FZF_DEFAULT_COMMAND="ag --ignore '*.pyc' --ignore '*.swp' --ignore '~*' --ignore 'node_modules' --ignore 'build' -g ''"

# GOPATH
export GOROOT=/opt/go
export GOPATH=$HOME/Workspace/golang
export PATH=$PATH:$PATH:$GOROOT/bin:$GOPATH/bin

# JPF
export JPF_ROOT="$HOME/Workspace/cin-master-degree/code/jpf"
export JPF_CORE=$JPF_ROOT/jpf-core

# git branch name
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

